{{- $serviceName := include "name" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}-{{ .Values.azureVoteBack.service.name }}
spec:
  ports:
    - port: {{ .Values.azureVoteBack.service.externalPort }}
  selector:
    app: {{ include "name" . }}
